### ISSUE TITLE
How do I use this to create a V0 CID?

### ISSUE THREAD

**Issue by MoonBoi9001** [alanshaw/ipfs-only-hash#20]
It seems that the CID created is of the format V1 CID. Is it possible to instead generate a V0 CID?

**Comment by MoonBoi9001** [comment]
ipfs add --only-hash --recursive <path to file>

the above does exactly what I need, leaving this for someone else incase they want it 

take out --recursive if you don't want the hash for every file in the directory

**Comment by JulienPlanchetCoineo** [comment]
Did you find a way to call recursive from the API ?

**Comment by MoonBoi9001** [comment]
> Did you find a way to call recursive from the API ?

Hey man yes I did, I actually found a better way that doesn't require it as well. When you upload files to ipfs inside a folder you can type the Cid of the folder into the URL and then append /X to the end to access the file inside that folder. 

For example if your file is called 1.png you can do f{URL}+ "/1.png" to access it. This way you don't need to compute thousands of different CID's.

**Comment by alanshaw** [comment]
Yes there's a `--cid-version` option in the CLI:

```console
$ ipfs-only-hash --help

  Just enough code to calculate the IPFS hash for some data

  Usage
    # get the cid v1 for the file 
    $ ipfs-only-hash <file>

    # get the cid v0 for data from stdin
    $ echo "hello world" | ipfs-only-hash --cid-version 0


$ echo "hello world" | ipfs-only-hash --cid-version 0
QmT78zSuBmuS4z925WZfrqQ1qHaJ56DQaTfyMUF7F8ff5o
```

If you're using this programmatically I _believe_ it outputs v0 CIDs by default but you can pass `cidVersion: 0` as an option if not. Docs for that are here: https://github.com/alanshaw/ipfs-only-hash#hashofinput-options-promisestring

I'd love a PR to add directory support...or maybe [fix up this one](https://github.com/alanshaw/ipfs-only-hash/pull/23).
